### ISSUE TITLE
CA Review: Making NFRs More Specific

### ISSUE THREAD

**Issue by sorainsm** [peter-michalski/LatticeBoltzmannSolvers#20]
@peter-michalski I think it's great that your NFRs cover all the software qualities. I think that some of them could be more specific. 

For Performance I suggest setting a minimum bound, and giving it an alias.
For example replace the current sentence with "The system shall be able to simultaneously run at minimum MIN_INSTANCES."

![image](https://user-images.githubusercontent.com/11723492/66539896-e1586880-eaf7-11e9-80ba-e43c7d25ec2a.png)

_EDIT: You could go a step further by stating some default test model it's able to run. For example "Given DEFAULT_PROBLEM, the system shall be able to simultaneously run a minimum of MIN_INSTANCES instances."_

**Comment by sorainsm** [comment]
Related to Robustness, there should be a Usability NFR regarding error messages/feedback.

![image](https://user-images.githubusercontent.com/11723492/66540096-aacf1d80-eaf8-11e9-8062-f188c211f5a9.png)

 _EDIT: @smiths would it be more appropriate to have an error message/feedback NFR under Robustness for this particular context?_

**Comment by smiths** [comment]
@sorainsm, please create a different issue for each logical issue.  The discussion in this thread is now on Performance and Robustness.  The discussion is cleaner if we have a separation of concerns.  :smile:

With respect to Performance, what we really want to do is to a posteriori describe the performance.  We don't need to a priori say what performance we expect.  In some cases we might need this, like if the calculations were part of a safety critical real time system.  In this case though, it is really usability that imposes performance requirements.  Rather than get into the specification of performance (and usability), the simplest solution is to punt this to the Verification and Validation plan.  My advice, at least for now, is to point to the VnV plan for the description of these NFRs.

With respect to robustness, this is an interesting one.  I definitely think there should be a requirement for error messages when the user enters invalid data.  The interesting consequence of this is that, once this is stated as a requirement, it is no longer a nonfunctional requirement.  It is a functional requirement.  :smile:.  Robustness is for how the system responds to unexpected errors.

**Comment by peter-michalski** [comment]
NFRs have been updated

**Comment by peter-michalski** [comment]
NFRs have been updated

**Comment by smiths** [comment]
@peter-michalski, please include the commit hash where the changes were made.

**Comment by peter-michalski** [comment]
I agree with @sorainsm 
I have made the necessary change to Performance in e291ad6296946a877c21844db772b6e33ebb0dd3

I have changed the wording for Robustness in 25853f1818603b5893eadefa86ebd5ba041bbfb5 .
