### ISSUE TITLE
Revise CA using given feedback (issue was originally a review issue)

### ISSUE THREAD

**Issue by peter-michalski** [peter-michalski/LatticeBoltzmannSolvers#21]
Hi @smiths , my CA has been ready for a few days. Please review. I had forgotten to create this issue then.

**Comment by smiths** [comment]
@peter-michalski, I have completed the review.  Comments are embedded in the document in caef121.  I will also attach a scan of a sheet listing additions I would like you to make.

This document is a difficult one to write.  I knew there was some interesting physics and math in the Lattice Boltzmann solvers, but I underestimated how much.  :smile: You did a good job "faking it," but I would like it eventually be a more useful document, especially since it is related to your MEng project.  Fortunately, we will have Dr. Motamed and  Mohammad (joint PhD student between Dr. Motamed and I) to help.  Mohammad should be joining us in January.

Please do not hesitate to ask questions as you revise the CA and work on your other documents.

In the attached document, I mention two web-pages:

https://feaforall.com/creating-cfd-solver-lattice-boltzmann-method/

http://andrew.gibiansky.com/blog/physics/lattice-boltzmann-method/

![Scan-Pg1](https://user-images.githubusercontent.com/1422000/68049382-1c922580-fcb9-11e9-931f-902d8f13e0db.jpg)
![Scan-Pg2](https://user-images.githubusercontent.com/1422000/68049388-2025ac80-fcb9-11e9-84aa-d94fcded9d7a.jpg)

**Comment by peter-michalski** [comment]
The DD TM and IM were updated/added in b226ef4a57b226248a37488e56b390c63140dcc8
