### ISSUE TITLE
Page 5 - Background Overview

### ISSUE THREAD

**Issue by Ao99** [peter-michalski/LatticeBoltzmannSolvers#5]
I feel that section 5.1 might need to be more abstract. Since it is an overview, do you think it can be more general and with fewer details here?

**Comment by sorainsm** [comment]
I agree with @Ao99.

I think the real issue is not the abstract of the problem description (it seems like a good overview of _what_ Lattice Boltzmann solvers _do_), but with the discussion of some of the variabilities this early. 

I've highlighted what I think are the "problem sentences"; if they are removed I think this section will read more appropriately.

![image](https://user-images.githubusercontent.com/11723492/66537555-d5b47400-eaee-11e9-8db3-3089d45089d1.png)

**Comment by peter-michalski** [comment]
thank you, updated

**Comment by peter-michalski** [comment]
I agree with this suggestion. The CA was updated in e291ad6296946a877c21844db772b6e33ebb0dd3 .
